FROM node:12.13-alpine As production
ENV HOME=/usr/src/app
ENV NODE_ENV=production
COPY package.json ${WORKDIR}/
COPY package-lock.json ${WORKDIR}/
RUN npm install --production
COPY . .

EXPOSE 2020

CMD ["npm","run", "start:prod"]